USE xyz;

SELECT * FROM employee;

-- LIMIT CLAUSE IT IS USED TO PRINT ONLY LIMITED ROWS
SELECT * FROM employee WHERE age>20 LIMIT 2;

-- ORDER  BY CLAUSE-ORDER EITHER DESCENDING OR ASCENDING ORDER
SELECT * FROM employee ORDER BY salary DESC;
SELECT * FROM employee ORDER BY age ASC;