USE xyz;

-- PERFORM PROCEDURE WITHOUT PARAMS
DELIMITER /
CREATE PROCEDURE getemployeedetails()
BEGIN
SELECT * FROM employee;
END /
DELIMITER ;

-- CALL THE PROCEDURE AFTER CREATION
CALL getemployeedetails;

-- PERFORM PROCEDURE WITH PARAMS
DELIMITER /
CREATE PROCEDURE getemployeeid(IN emp_id INT)
BEGIN
SELECT * FROM employee
WHERE id=emp_id;
END /
DELIMITER ;

-- FOR DROP PROCEDURE
DROP PROCEDURE IF EXISTS getemployeeid;

-- CALL PROCEDURE
CALL getemployeeid(6);
