USE xyz;

SELECT * FROM employee;

-- RENAME COMMAND WITHOUT ALTER COMMAND TO  CHANGE TABLE NAME
RENAME TABLE employee1 TO employee;

-- RENAME DATABASE WITHOUT ALTER COMMAND
RENAME DATABASE xyz TO special;
