USE xyz;
SELECT * FROM customer;
SELECT * FROM c_order;

-- PERFORM UNION OPERATION
SELECT id 
FROM customer
UNION   -- IT GIVES THE VALUES OF TWO TABLES BY REMOVING THE DUPLICATES
SELECT id
FROM c_order;


-- PERFORM UNION ALL OPERATION
SELECT id
FROM customer
UNION ALL  -- IT GIVES ALL SELECTED VALUES NOT REMOVING THE DUPLICATES
SELECT id
FROM c_order;