CREATE DATABASE xyz;
USE xyz;

CREATE TABLE employee(
id INT PRIMARY KEY,
name VARCHAR(50),
age INT,
department VARCHAR(50),
city VARCHAR(50),
salary INT
);

INSERT INTO employee
(id,name,age,department,city,salary)
VALUES
(1,'RITURAJ',23,'CSE-AIML','MORADABAD',200000),
(2,'HAMMAD',23,'CSE-DS','ALIGARH',300000),
(3,'ANMOL',23,'CSE','BIJNOR',100000),
(4,'ANUBHAV',21,'CS','SHARANPUR',600000),
(5,'SHEWTA',45,'CSE-AIML','BIKANER',900000),
(6,'SURAJ',20,'CSE','VARANASI',400000);

SELECT * FROM employee;


-- UPDATE employee
-- SET age=23
-- WHERE name="SHEWTA";

SET SQL_SAFE_UPDATES = 0;

-- UPDATE THE AGE FROM 45 TO 23 WHERE NAME IS SHWETA
UPDATE employee
SET age = 23
WHERE name = 'SHEWTA';

-- WRITE QUERY TO UPDATE THE NAME OF EMPLOYEE FROM HAMMAD TO REETESH
UPDATE employee
SET name='REETESH'
WHERE name='HAMMAD';


